name: comfyui_remote
description: "ComfyGo - ComfyUI Remote Client"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  gal: ^2.3.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  image_picker: ^1.0.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^18.0.0
  permission_handler: ^11.3.0
  share_plus: ^10.1.0
  file_picker: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/workflow_api.json
    - assets/workflow_api_2.json
    - assets/icon.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/icon.png"
  android: true
  ios: true
